//SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;
import "./pbt/PBTSimple.sol";
import "@openzeppelin/contracts/access/Ownable.sol";


contract Season1byMazh is PBTSimple, Ownable{

    /// @dev The chip and tokenId arrays have different lengths.
    error ArrayLengthMismatch();

    /// @dev No chips were provided to pair.
    error NoChipsProvided();

    /// @dev The signature duration window is zero, which would reject every scan.
    error MaxDurationWindowIsZero();

    /// @dev A `tokenId` of zero cannot be paired, as it is what an unpaired chip maps to.
    error TokenIdIsZero();

    /// @notice Emitted when the base URI is updated
    /// @param baseURI The new base URI
    event NewBaseURI(string baseURI);


    string public baseURI;


    /// @notice Initialize a mapping from chipAddress to tokenId.
    /// @param chipAddresses The addresses derived from the public keys of the chips
    /// @param tokenIds The tokenIds to map to the addresses
    /// @param maxDurationWindow Maximum duration for a signature to be valid since the timestamp used in the signature.
    /// @param baseURI_ The base URI for the PBTs
    constructor(
        address[] memory chipAddresses,
        uint256[] memory tokenIds,
        uint256 maxDurationWindow,
        string memory baseURI_
    ) 
        PBTSimple("Season1byMazh", "S1M", maxDurationWindow){
            if (chipAddresses.length != tokenIds.length) revert ArrayLengthMismatch();
            if (chipAddresses.length == 0) revert NoChipsProvided();
            if (maxDurationWindow == 0) revert MaxDurationWindowIsZero();
            for (uint256 i = 0; i < chipAddresses.length; i++) {
                if (tokenIds[i] == 0) revert TokenIdIsZero();
                _setChip(tokenIds[i], chipAddresses[i]);
            }
            baseURI = baseURI_;
            emit NewBaseURI(baseURI_);
        }

    /// @notice Set the base URI for the PBTs
    /// @param baseURI_ The new base URI
    function setBaseURI(string calldata baseURI_) external onlyOwner{
        baseURI = baseURI_;
        emit NewBaseURI(baseURI_);
    }

    /// @notice Get the base URI for the PBTs, internally
    /// @return The base URI for the PBTs
    function _baseURI() internal view override returns (string memory){
        return baseURI;
    }


    /// @notice Disabled. An ownerless contract could never repoint `baseURI`,
    ///         freezing the metadata at whatever directory was last set.
    function renounceOwnership() public virtual override {
        revert("Ownable: renounceOwnership is not allowed");
    }

    /// @param to the address to which the PBT will be minted
    /// @param chipId the chip address being minted
    /// @param chipSignature the signature generated by the chip
    /// @param signatureTimestamp the timestamp used in the signature
    /// @param extras misc data, for extensions or custom logic in mint
    function mint(
      address to,
      address chipId,
      bytes memory chipSignature,
      uint256 signatureTimestamp,
      bytes memory extras
    ) external returns (uint256) {
        return _mint(to, chipId, chipSignature, signatureTimestamp, extras);
    }

}