//SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;
import "@openzeppelin/contracts/access/Ownable.sol";
import "@chiru-labs/pbt/src/v2/PBTSimple.sol";

contract Season1byMazh is PBTSimple{

    constructor(
        address[] memory chipAddresses,
        uint256[] memory tokenIds,
        uint256 maxDurationWindow
    ) 
        PBTSimple("Season1byMazh", "S1M", maxDurationWindow){
           for (iuint256 i = 0; i < chipAddresses.length; i++) {
                _setChip(tokenIds[i], chipAddresses[i]);
            }
        }
    /// @param to the address to which the PBT will be minted
    /// @param chipId the chip address being minted
    /// @param chipSignature the signature generated by the chip
    /// @param signatureTimestamp the timestamp used in the signature
    /// @param extras misc data, for extensions or custom logic in mint
    function mint(
      address to,
      address chipId,
      bytes memory chipSignature,
      uint256 signatureTimestamp,
      bytes memory extras
    ) external returns (uint256) {
        return _mint(to, chipId, chipSig, sigTimestamp, extras);
    }

}